### ISSUE TITLE
Windows install error

### ISSUE THREAD

**Issue by spiderZhengLi** [ZhengYinan-AIR/FISOR#3]
ERROR: Could not find a version that satisfies the requirement jaxlib==0.4.9+cuda12.cudnn88 (from versions: 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29, 0.4.30)
ERROR: No matching distribution found for jaxlib==0.4.9+cuda12.cudnn88

**Comment by Facebear-ljx** [comment]
Hi! We only test our code on Linux Ubuntu 20.0.4 and 22.04 LTS. It seems that JAX does not support CUDA on Windows, so you cannot install the cuda-version jaxlib on Windows system (see https://github.com/google/jax?tab=readme-ov-file#supported-platforms for details).
