### ISSUE TITLE
results question

### ISSUE THREAD

**Issue by Chenrf1121** [ZhengYinan-AIR/FISOR#4]
After running the default code, the results are quite different. Is this because of the data set? Different initial states have a greater impact on the results?

**Comment by ZhengYinan-AIR** [comment]
Hello, I directly used the official dsrl dataset without any post-processing, and the testing did not specify an initial position. Recent works have reported scores using FISOR that are comparable to, or even better than, those reported in our paper. Additionally, FISOR used the same set of parameters across all tasks. By adjusting parameters specifically for individual tasks, you can potentially achieve better outcomes.

**Comment by Chenrf1121** [comment]
Yes, I measure run default code three times that is a good choose, just sometime the cost score is unstable, (better or worse), I believe that is common. This repo. is wonderful.

**Comment by Chenrf1121** [comment]
Would you recommend some work that reports the scores of FISOR on the dsrl dataset?

**Comment by ZhengYinan-AIR** [comment]
Yes, testing with more seeds can provide a more accurate evaluation of instability issues. Another factor is that while diffusion can enhance model performance, it might also lead to instability and introduce greater randomness. There should be extensive research on how to generate stable actions. Regarding the articles that reported FISOR scores, you might want to check out recent papers on safe offline learning and [submissions to ICLR](https://openreview.net/group?id=ICLR.cc/2025/Conference#tab-active-submissions)
